toggle profile switches instead of individual devices
mammuth/ha-fritzbox-tools pull request #110
Opened 2020-08-21 09:52 UTC by AaronDavidSchneider

With this PR, profiles are toggled (by changing the online time from unlimited to never and vice versa). The previous switch for device profiles reassigned devices to groups which has been a huge overkill. 

I tested (as appropriate):
- [ ] Get/Set port switch
- [ ] Get/Set 2.4 Ghz wifi
- [ ] Get/Set 5 Ghz wifi
- [ ] Get/Set guest wifi switch
- [ ] Get/Set call deflections
- [ ] Connectivity sensor
- [x] Yaml Mode

Closes issue #109 

Remaining Question:
- [x] Does a sid (session id) expire? Needs longer term test. Could easily be fixed in underlying library.
Shouldn't be a problem with release 0.2 of fritzprofiles. Could have been one of the problems of the usage of the other library.

- [x] Naming of `CONF_USE_DEVICES` and  `DEFAULT_USE_DEVICES` have been kept untouched. Should they be changed?

2020-08-26 10:38 UTC, AaronDavidSchneider commented
I updated the error handling to fix issue #70. The problem has been that the error alway occured in __init__ of Fritzboxtools. Therefore we need to grab this error already there.

2020-08-26 13:44 UTC, AaronDavidSchneider commented
Since the error messages are indeed really helpful, I added an additional error message, when a profile doesn't exist. With this  update, a user can see the following Errors:

Wrong credentials:
![Screenshot 2020-08-26 at 15 39 54](https://user-images.githubusercontent.com/7556347/91310961-cb58a280-e7b2-11ea-8b94-8966a7d13c7f.png)

Attempt to use profile switches, but "Anmeldung im Heimnetzwerk mit Nutzername und Passwort" disabled (fritzconnection doesn't seem to care here, since it uses the fritz-api):
![Screenshot 2020-08-26 at 15 42 06](https://user-images.githubusercontent.com/7556347/91310953-ca277580-e7b2-11ea-94e6-87523f258762.png)

Attempt to use profile switches, but profiles mentioned are not existant:
![Screenshot 2020-08-26 at 15 40 43](https://user-images.githubusercontent.com/7556347/91310959-cac00c00-e7b2-11ea-9def-096b39d9577f.png)

2020-08-26 16:08 UTC, AaronDavidSchneider commented
Forgot to mention: Latest commit closes #101 and #102.

2020-08-29 09:20 UTC, mammuth requested changes
Looks good overall, nice! I added some smaller comments 😊

2020-08-29 09:20 UTC, mammuth commented on custom_components/fritzbox_tools/switch.py
> +        self._is_available = True  # set to False if an error happend during toggling the switch
This comment doesn't make sense anymore, right?

2020-08-29 09:20 UTC, mammuth commented on custom_components/fritzbox_tools/switch.py
>                  self._is_on = True  # TODO: Decide on default behaviour
Shouldn't we also set `_is_available` in `if status == "never"` and `elif status == "unlimited"`? Otherwise, it might be unavailable until the integration gets reloaded, right?

2020-08-29 09:20 UTC, mammuth commented on custom_components/fritzbox_tools/switch.py
> +        await self._async_fetch_update()
If we don't have any logic in `#async_update` anymore, do we actually still need `#_async_fetch_update` or can't we just move everything here?

2020-08-29 09:20 UTC, mammuth commented on custom_components/fritzbox_tools/switch.py
> +            state = "never"
For these simple assignments, you could use ternary assignments: `state = "unlimited" if turn_on else "never"`

2020-08-29 09:20 UTC, mammuth commented on custom_components/fritzbox_tools/translations/de.json
>              "setup_devices": {
Shouldn't we also change this dictionary key to eg. `setup_profiles`?

2020-08-29 09:20 UTC, mammuth commented on custom_components/fritzbox_tools/translations/de.json
> +                "description": "Device profiles needs at least one profile.\nleave it empty if you don't need it.\nDocumentation: https://github.com/mammuth/ha-fritzbox-tools",
We could probably also translate the messages to German when we already touch the files 🤔

2020-08-29 12:50 UTC, AaronDavidSchneider commented on README.md
> +  profiles: # Optional. Needed if you want to control the profiles of your network devices.
Good idea. I will add that

2020-08-29 12:50 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/__init__.py
> +                address=host, port=port, user=username, password=password, timeout=30.0
we could extend it to 60 seconds. What do you think?

2020-08-29 12:51 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/config_flow.py
> +            profiles = profiles.replace(' ', '').split(',')
probably not. I will test it and try to fix it. Thanks for the hint!

2020-08-29 12:51 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/strings.json
> +                    "profiles": "Device profiles: Comma seperated list of Profiles"
Good idea!

2020-08-29 12:52 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/strings.json
> +            "connection_error_profiles": "Profile switches only work if login via user and password is enabled in the FRITZ!Box",
Good idea! I will add it.

2020-08-29 12:52 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/switch.py
> +        self._is_available = True  # set to False if an error happend during toggling the switch
Yes thats true. I will change that.

2020-08-29 12:52 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/switch.py
>                  self._is_on = True  # TODO: Decide on default behaviour
I will provide a fix. Thanks for the hint.

2020-08-29 12:53 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/switch.py
> +        await self._async_fetch_update()
Thats true. I will update that.

2020-08-29 12:53 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/switch.py
> +            state = "never"
thats a good idea.

2020-08-29 12:53 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/translations/de.json
>              "setup_devices": {
I will change that.

2020-08-29 12:54 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/translations/de.json
> +                "description": "Device profiles needs at least one profile.\nleave it empty if you don't need it.\nDocumentation: https://github.com/mammuth/ha-fritzbox-tools",
Yes... but that sounds like a lot of work.... :D

2020-08-29 15:11 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/config_flow.py
> +            profiles = profiles.replace(' ', '').split(',')
Should work now

2020-08-29 15:14 UTC, AaronDavidSchneider commented
Thanks for the feedback! I implemented your requests. Also: I changed all names with devices to access profiles. Thats the word used in the english version of the fritzbox (changed my language settings from german to english)
<img width="1157" alt="Screenshot 2020-08-29 at 17 13 52" src="https://user-images.githubusercontent.com/7556347/91640033-06f5a580-ea1b-11ea-9b3a-7193a416bbbf.png">

2020-08-30 17:56 UTC, mammuth approved these changes

2020-08-30 18:04 UTC, mammuth commented
Nice, should I merge and create a pre-release? I think HACS somehow supports this so people who subscribed to beta updates of the integration can get it first.

2020-08-30 18:22 UTC, AaronDavidSchneider commented
Yes that sounds good!

2020-08-30 18:24 UTC, merged