[WIP] Discovery
mammuth/ha-fritzbox-tools pull request #116
Opened 2020-10-01 08:18 UTC by AaronDavidSchneider

Extension of fritzbox tools to use the discovery component. Work in progress. Help is appreciated :D

I tested (as appropriate):
- [ ] Get/Set port switch
- [ ] Get/Set 2.4 Ghz wifi
- [ ] Get/Set 5 Ghz wifi
- [ ] Get/Set guest wifi switch
- [ ] Get/Set call deflections
- [ ] Connectivity sensor
- [ ] Yaml Mode

2020-10-01 09:42 UTC, AaronDavidSchneider commented
Seems to work. However, YAML mode seems to be broken. Need to find a fix for that.

2020-10-01 10:12 UTC, AaronDavidSchneider commented
YAML error fixed. Ready for review 👯‍♂️

2020-10-01 11:32 UTC, AaronDavidSchneider commented
Small addition: Take port from discovery.

2020-10-01 11:37 UTC, AaronDavidSchneider commented
Discovery (I have two fritzboxes, one is the modem (7530), the other one is just a repeater (mesh client)):
<img width="1127" alt="Screenshot 2020-10-01 at 13 33 51" src="https://user-images.githubusercontent.com/7556347/94804268-d2df1d00-03ea-11eb-8e07-608d24111428.png">

When clicking on configure:
<img width="556" alt="Screenshot 2020-10-01 at 13 34 08" src="https://user-images.githubusercontent.com/7556347/94804272-d4104a00-03ea-11eb-8c84-d0d82863f130.png">

Once one fritzbox is added the other fritzbox will not get discovered anymore (only one component allowed) once hass is restarted.

2020-10-04 19:31 UTC, mammuth requested changes

2020-10-04 19:31 UTC, mammuth commented on custom_components/fritzbox_tools/config_flow.py
> +        errors = {}
Duplicated declaration

2020-10-04 19:31 UTC, mammuth commented
Pretty cool! 🚀  Only left a small comment.

2020-10-05 05:43 UTC, AaronDavidSchneider commented
Thanks for the review @mammuth. I removed the duplicate variable `errors`

2020-10-06 15:17 UTC, AaronDavidSchneider commented
Shall we merge this PR @mammuth?

2020-10-06 15:51 UTC, mammuth commented
Yes. It's no breaking change that should be announced in the release notes, right?

2020-10-06 15:52 UTC, AaronDavidSchneider commented
> Yes. It's no breaking change that should be announced in the release notes, right?

No. Thanks!

2020-10-06 16:09 UTC, merged