Add 'reauth' config flow
mammuth/ha-fritzbox-tools pull request #143
Opened 2021-01-24 14:56 UTC by jloehr

With the recent security disclosure, users are advised to change their credentials.

After changing the credentials on the FRITZ!Box, this custom component didn't provide any means to change the entered credentials through the new Integration UI.

The Config Entry Flow supports [Reauthentication](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#reauthentication). This PR implements this flow, to update the credentials for a FRITZ!Box in case the setup fails due to an `FritzConnectionException` error.

Screens how it appears on the integration page:
![image](https://user-images.githubusercontent.com/4631548/105633947-d2680780-5e5b-11eb-9934-43a0974e92d0.png)

(Credentials are prefilled with the config data)
![image](https://user-images.githubusercontent.com/4631548/105633973-ec094f00-5e5b-11eb-8419-021eaa7aa972.png)

Success dialog unfortunately shows 'Aborted'. This is due to using an abort result, to resolve the flow. However this is from the official docs. Providing an appropriate flow resolve is up to the Home Assistant Core devs. 
![image](https://user-images.githubusercontent.com/4631548/105634032-55895d80-5e5c-11eb-8ec1-a40b74ab5c98.png)

I tested (as appropriate):
- [ ] Get/Set port switch
- [ ] Get/Set 2.4 Ghz wifi
- [ ] Get/Set 5 Ghz wifi
- [ ] Get/Set guest wifi switch
- [ ] Get/Set call deflections
- [ ] Connectivity sensor
- [ ] Yaml Mode

2021-01-24 15:00 UTC, mammuth commented
Super cool! :tada:

@AaronDavidSchneider implemented most of the current config flow, he'd be the best to review this change I'd say.

2021-01-24 16:37 UTC, AaronDavidSchneider commented
Wow! That looks great!
I will test it tomorrow and give some feedback.
But from what I can see, this looks already very good.

2021-01-24 16:55 UTC, jloehr commented
Thanks! One thing I wasn't sure about, is the "already_in_progress" guard and whether it is needed for reauth as well.

I also had some changes to trigger the reauth in case the Host or Port of the FRITZ!Box changed. Though SSDP interfered with that, as it did update the Host/IP itself. So I removed my changes in that regard.

2021-01-25 08:24 UTC, AaronDavidSchneider commented
> Thanks! One thing I wasn't sure about, is the "already_in_progress" guard and whether it is needed for reauth as well.
> 
> I also had some changes to trigger the reauth in case the Host or Port of the FRITZ!Box changed. Though SSDP interfered with that, as it did update the Host/IP itself. So I removed my changes in that regard.

I think it should be sufficient to change password and user in case of changes. Changes of the host (port, ip) should in my oppinion require to readd the integration.

I think the best idea would be to wait with this PR until https://github.com/home-assistant/core/issues/45497 is resolved.
At this stage of fritzbox-profiles it is best to keep both config flows similar.

2021-01-25 08:47 UTC, AaronDavidSchneider commented
I tested this PR by changing the password of the user. I get the following errors:

```
2021-01-25 09:41:07 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up fritzbox_tools platform for binary_sensor
Traceback (most recent call last):
  File "/Users/schneider/codes/HA/home-assistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/binary_sensor.py", line 29, in async_setup_entry
    async_add_entities([FritzBoxConnectivitySensor(fritzbox_tools)], True)
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/binary_sensor.py", line 41, in __init__
    self.entity_id = ENTITY_ID_FORMAT.format(f"fritzbox_{self.fritzbox_tools.fritzbox_model}_connectivity")
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/__init__.py", line 285, in fritzbox_model
    return self._device_info["model"].replace("FRITZ!Box ", "")
AttributeError: 'FritzBoxTools' object has no attribute '_device_info'
2021-01-25 09:41:07 INFO (MainThread) [homeassistant.components.switch] Setting up switch.fritzbox_tools
2021-01-25 09:41:07 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/switch.py", line 137, in _create_wifi_switches
    [FritzBoxWifiSwitch(fritzbox_tools, net, networks[net])],
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/switch.py", line 551, in __init__
    self.entity_id = ENTITY_ID_FORMAT.format(f"fritzbox_{self._fritzbox_tools.fritzbox_model}_{id}")
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/__init__.py", line 285, in fritzbox_model
    return self._device_info["model"].replace("FRITZ!Box ", "")
AttributeError: 'FritzBoxTools' object has no attribute '_device_info'
2021-01-25 09:41:07 ERROR (SyncWorker_0) [custom_components.fritzbox_tools.switch] Port switches could not be enabled. Check if your fritzbox is able to do port forwardings!
Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 58, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/switch.py", line 72, in _create_port_switches
    connection_type = fritzbox_tools.connection.call_action(
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response
    raise_fritzconnection_error(response)
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 68, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Mon, 25 Jan 2021 08:41:05 GMT

2021-01-25 09:41:07 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/switch.py", line 117, in _create_profile_switches
    if len(fritzbox_tools.profile_switch) > 0:
AttributeError: 'FritzBoxTools' object has no attribute 'profile_switch'
2021-01-25 09:41:07 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 58, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/schneider/codes/HA/home-assistant/config/custom_components/fritzbox_tools/switch.py", line 34, in _create_deflection_switches
    deflections_response = fritzbox_tools.connection.call_action("X_AVM-DE_OnTel:1", "GetNumberOfDeflections")
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response
    raise_fritzconnection_error(response)
  File "/Users/schneider/codes/HA/home-assistant/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 68, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Mon, 25 Jan 2021 08:41:05 GMT
```

I did not get the reconfigure config flow. Could you explain again how you reach the reauth step?

2021-01-25 08:54 UTC, AaronDavidSchneider requested changes
Looks good so far. I have only one small comment.

I am not sure why it doesn't work on my setup.

2021-01-25 08:54 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/__init__.py
> +
I think a better place for these would be const.py

2021-01-26 18:48 UTC, jloehr commented
> I think the best idea would be to wait with this PR until [home-assistant/core#45497](https://github.com/home-assistant/core/issues/45497) is resolved.
> At this stage of fritzbox-profiles it is best to keep both config flows similar.

Agree, I started working on  PR for Core and will rework this PR once the other is merged into Core.

2021-01-29 15:08 UTC, jloehr commented
Ok, home-assistant/core#45497 is resolved by home-assistant/core#45587

I updated the PR to incorporate some changes from the core PR.
- The entry object can be passed in and reused to remove the looped look up.
- Remove prefilling user password to be consistent with the core PR and other core component flows.

2021-01-29 15:09 UTC, jloehr commented on custom_components/fritzbox_tools/__init__.py
> +
Done

2021-03-02 14:08 UTC, chemelli74 commented
Confirm to work perfectly.

2021-03-07 09:52 UTC, mammuth commented
At a short glimpse it looks like the changes @AaronDavidSchneider requested were implemented right? @jloehr 

Is this ready to go?

2021-03-07 14:25 UTC, AaronDavidSchneider requested changes
I can confirm that it works once I restart HA. The implementation also looks good.
However, is it possible without restarting HA first?

Here is the error log that I get upon changing my password:
```
2021-03-07 15:21:23 ERROR (MainThread) [custom_components.fritzbox_tools.switch] Authorization Error: Please check the provided credentials and verify that you can log into the web interface.
Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 58, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/personal/hass/config/custom_components/fritzbox_tools/switch.py", line 584, in _async_fetch_update
    wifi_info = await self.hass.async_add_executor_job(lambda: self._fritzbox_tools.connection.call_action(
  File "/Users/schneider/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/schneider/codes/personal/hass/config/custom_components/fritzbox_tools/switch.py", line 584, in <lambda>
    wifi_info = await self.hass.async_add_executor_job(lambda: self._fritzbox_tools.connection.call_action(
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response
    raise_fritzconnection_error(response)
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 68, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Sun, 07 Mar 2021 14:21:23 GMT

2021-03-07 15:21:23 ERROR (MainThread) [custom_components.fritzbox_tools.switch] Authorization Error: Please check the provided credentials and verify that you can log into the web interface.
Traceback (most recent call last):
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 58, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/Users/schneider/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schneider/codes/personal/hass/config/custom_components/fritzbox_tools/switch.py", line 584, in _async_fetch_update
    wifi_info = await self.hass.async_add_executor_job(lambda: self._fritzbox_tools.connection.call_action(
  File "/Users/schneider/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/schneider/codes/personal/hass/config/custom_components/fritzbox_tools/switch.py", line 584, in <lambda>
    wifi_info = await self.hass.async_add_executor_job(lambda: self._fritzbox_tools.connection.call_action(
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response
    raise_fritzconnection_error(response)
  File "/Users/schneider/codes/personal/hass/venv/lib/python3.8/site-packages/fritzconnection/core/soaper.py", line 68, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Sun, 07 Mar 2021 14:21:23 GMT

2021-03-07 15:21:34 ERROR (MainThread) [custom_components.fritzbox_tools] Unable to setup FRITZ!Box Tools component
```

2021-03-07 14:27 UTC, AaronDavidSchneider commented
Is it possible to trigger the reauth step directly from within the update step of e.g. the wifi switch?

2021-03-07 14:31 UTC, AaronDavidSchneider commented on custom_components/fritzbox_tools/config_flow.py
> +        return self.async_abort(reason="reauth_successful")
this line makes no sense. We don't want to abort here?!
Maybe Change to `return self.hass.config_entries.async_reload(self._entry.entry_id)` instead?

2021-03-07 14:56 UTC, jloehr commented on custom_components/fritzbox_tools/config_flow.py
> +        return self.async_abort(reason="reauth_successful")
As of now, that's the official documented way on how to resolve the reauth flow. (See https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#reauthentication)
I don't like it either, though it's better to keep it aligned to the docs and raise an issue about that in the core repo.

2021-03-07 15:06 UTC, jloehr commented
> Is it possible to trigger the reauth step directly from within the update step of e.g. the wifi switch?
 
HA Core Integrations do not trigger reauth on the fly either, only on HA restart. So there is no official reference for that.
So I'm not entirely sure about on how to approach it, but that would probably require each and every call to `fritzconnection` to `try ... catch` `FritzConnectionException` and maybe trigger an integration reload?

What are your thoughts on that? My preference would be to leave this PR as is, so the integration is on par with the Core `fritzbox` integration. Then after checking back with Core development, adding on the fly reauth trigger in a separate PR.

2021-03-07 15:24 UTC, AaronDavidSchneider approved these changes
That makes sense.
Thanks again for the implementation!

2021-03-16 19:08 UTC, merged

2021-03-16 19:10 UTC, mammuth commented
Thanks a lot @jloehr!

This change is release in `1.15.0`.